language: java
jdk:
  - oraclejdk7
before_install:
- travis/before_install.sh
script: mvn -DfinalName=sharpen test -q

notifications:
  email:
    recipients:
    - hzaldivar79@gmail.com
    on_success: always
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: 
    - src/target/sharpen-jar-with-dependencies.jar
    - code_quality_report.txt
  on:
    repo: vackup/sharpen
    all_branches: true
    tags: false
after_success:
  - mvn install -q -Pqulice -DskipTests -DfinalName=sharpen > code_quality_report.txt || true
